const data = {
  products: [
    {
      Name: 'Waist Trousers',
      slug: 'waist-trouser',
      category: 'Shirts',
      image: '/images/p1.jpg',
      price: 1200,
      countInstock: 10,
      brand: 'Nike',
      rating: 4.5,
      numReviews: 10,
      description: 'Solid Texture Elastic Waist Trousers',
    },
    {
      Name: 'Maxi dress',
      slug: 'maxi-dress',
      category: 'Dress',
      image: '/images/p2.jpg',
      price: 4000,
      countInstock: 7,
      brand: 'Cider',
      rating: 3.5,
      numReviews: 10,
      description: 'Texture Lace Up Tiered Maxi Dress',
    },
    {
      Name: 'Adidas Fit Pant',
      slug: 'adidas-fit-pant',
      category: 'Pants',
      image: '/images/p3.jpg',
      price: 1800,
      countInstock: 8,
      brand: 'Puma',
      rating: 4.8,
      numReviews: 25,
      description: 'high quality pant',
    },
    {
      Name: 'Elastic Waist Wide Leg Trousers',
      slug: 'wide-leg',
      category: 'Trousers',
      image: '/images/p4.jpg',
      price: 1400,
      countInstock: 4,
      brand: 'Klarna',
      rating: 3.9,
      numReviews: 10,
      description: 'high quality trouser',
    },
  ],
};

export default data;
